"""NMT state / command string constants."""
OPERATIONAL = 'OPERATIONAL'
STOPPED = 'STOPPED'
SLEEP = 'SLEEP'
STANDBY = 'STANDBY'
PRE_OPERATIONAL = 'PRE-OPERATIONAL'
INITIALISING = 'INITIALISING'
RESET = 'RESET'
RESET_COMMUNICATION = 'RESET COMMUNICATION'
